### ISSUE TITLE
Values for MKS Controller

### ISSUE THREAD

**Issue by athenawisdoms** [yoelk/Instrumentino#11]
Hi there, which MKS MFC controller does Instrumentino support?

Looking at MKS MFC, how do you do the voltage-pressure mapping for the "Flow Signal Output" and "Set Point Input" pins?

**Comment by yoelk** [comment]
It's the old black kind.
Here is the model number of one of them:
1179A11CS1BK

They require a 0-5 volts signal for 0-100% flow, so when you type 50% in
the GUI, Instrumentino tells Arduino to write 2.5V to the output pin.

Does this answer your question? I'm not sure I understood it correctly.

**Comment by athenawisdoms** [comment]
Yes that answered it!

How do you convert the voltage reading from the "Flow Signal Output" to an sccm value?

**Comment by yoelk** [comment]
Well, you'd have to look at the full scale of the MFC and multiply it by
the percentage you put into Instrumentino. I guess each MFC will have a
different full scale

**Comment by athenawisdoms** [comment]
Thank you that makes sense. I'm trying to understand how the electronics and code work before using it. Sorry for asking too many questions below:

What is are the pins labelled `MKS Test Point` and `Optional Input` for?

Why did you connect the `NC` pins to `Signal Common` rather than leave it open like the pin `MKS TP`?

Why did you connect `Chassis Ground` to `Signal Common` instead of to `Power Common`?

For gas to flow through the MFC, do we supply a 0.0 VDC to pin 4 and 5.0 VDC to pin 3?

Why is the `Set Point Input` driven through an I2C rather than directly from the Arduino output pins?

**Comment by yoelk** [comment]
I'm not sure about the *MKS Test* and *Optional Input* pins, I don't use
them.

I connected the NC pins to ground because it made the ground connections
easier (look at the board file). I don't think it should matter.

Chasis ground might have been better connected to power common, perhaps
you're right.

Which pins 4 and 3 are you referring to? the MFC's or Arduino's pins?
To set the output we write an I2C command to the I2C bus.

You need an analog output, which Arduino boards usually don't have.
An I2C DAC is one way to go, which we found works quite well.

**Comment by athenawisdoms** [comment]
Sorry, was referring to pin 7 `Valve Open (TTL low)` and pin 5 `Valve Close (TTL low)` on the MFC.

Will the Arduino's PWM output not work as an analog output for the MFC?

**Comment by yoelk** [comment]
you can use the PWM output with a low pass filter, and we also used to do
it this way.
But the DAC gives you a much nicer signal out.

**Comment by athenawisdoms** [comment]
Looking more closely at the schematics, should the MAX517's SCL and SDA be connected to Arduino's D4 and D5 instead of A4 and A5 as those seem to be Nano's SCL/SDA pins.

Whats the purpose of the 330R resistors R1/R3 and 10k resistors R8/R2?

**Comment by yoelk** [comment]
Where did you get this information?
According to this datasheet <http://www.arduino.cc/en/Main/ArduinoBoardNano>
its A4,A5.

For your second question, please look here
<http://www.chemie.unibas.ch/~hauser/open-source-lab/Arduino-DAC/Arduino-DAC.html>
.

**Comment by athenawisdoms** [comment]
I got the info from another source
![](http://2.bp.blogspot.com/-nGbwbpqz7xU/UJW2yoRcd7I/AAAAAAAATdI/KG95uVsLgdM/s1600/Arduino%2Bnano%2BPinout.png)

Thank you, I assume replacing the 4.7k resistors in your references with 10k in your schematics does affect anything much.

**Comment by yoelk** [comment]
Yes, that should be fine.
