### ISSUE TITLE
instrumentino-1.0-py2.7.egg not in Download Package

### ISSUE THREAD

**Issue by johnwetzel** [yoelk/Instrumentino#28]
I downloaded the zip file from GitHub and instrumentino-1.0-py2.7.egg was not located in supplementarymaterial/Instrumentino/dist.  There was no dist folder. I am trying to install and get this to work on a Mac. I also have very little Python experience.

**Comment by yoelk** [comment]
You're right, I should have uploaded the /dist library to GitHub as well.
I did it now and you can get the code with the .egg file (under /instrumentino/dist) in the most recent release:
https://github.com/yoelk/Instrumentino/releases

also, you can download the .egg file directly from PyPi:
https://pypi.python.org/pypi/instrumentino

I'll be glad to help if you run into further difficulties,
Joel

**Comment by johnwetzel** [comment]
Thanks so much Joel!
