### ISSUE TITLE
example runs slows down and hang on raspberry pi

### ISSUE THREAD

**Issue by Ravasz** [yoelk/instrumentino#45]
Hi there,

Thanks for writing Instrumentino, really useful stuff.
After testing it successfully on my laptop, now I am trying to set it up on a raspberry pi, but this does not seem to work. I am wondering if anyone has an idea what I'm doing wrong here.

When I start the example run "Arduino pins" on the pi (after setting up everything correctly), the program slows to a crawl after connecting to the Arduino and after a minute or two the GUI stops responding completely. It does not run out of CPU or memory, it simply hangs without any error message and I have to kill the process. If I restart the program it runs again for a minute or two and hangs again.

The problem seems to be with updating the GUI window. The logfiles are still being written long after the GUI hangs so the program keeps running, it just fails to visualize anything and the GUI does not respond to clicks if it renders at all.

The pi does not allow really robust debuggers to run but I can run strace to monitor system calls. It seems ArduinoPins.py spends most of its time seeking specific lines in /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf for some odd reason over and over again. I am not sure if this is the exact problem but I am not even sure how to troubleshoot this as I get no error message, just see the window freeze. Here is the complete output of Strace if anyone's interested: https://github.com/Ravasz/instrumentino/blob/master/documents/example_run_ArduinoPins.py/logfile3

I can reproduce this on two different pi-s and two separate arduinos while it was not present on a laptop.

Any help or suggestions as to why the example run hangs on a raspberry pi would be much appreciated.

**Comment by yoelk** [comment]
Hi, I'm happy to hear you like it.
And really cool you're trying to run it on a Pi.
Instrumentino v1 uses wxPython, and I think at the time I've been using
version around 2.8 (sorry, I haven't kept track in a requirements file, was
a newbie back then).
Might it be related to the wx version? Can wxPython even run well on a Pi?
I have no experience there yet.

btw, have you had a look at v2 I've been developing? Unfortunately I ran
out of time resources to complete it, but if I'd get some help, v2 would be
far superior!
Always fishing around to find interested parties for that endeavor... :)

**Comment by Ravasz** [comment]
Hi,
Sorry for the late reply. Yes its probably a wxPython issue with the v1 on the pi, which means I won't be patching it as it might take ages to sort out some bug in the wxPython source code. WxPython does run on the pi, I wouldn't say well, but it does run.

I would love to contribute to the v2, thanks the invitation. Unfortunately I too have to be strict about what I commit time to, so now I should just be looking for a quick solution to control stuff from a pi through an arduino. Either way I'll keep an eye on the project and thanks again putting this all together, its a good starting point for all sorts of things.
