### ISSUE TITLE
Trouble compiling controlino

### ISSUE THREAD

**Issue by daniellikessoccer** [yoelk/Instrumentino#5]
Instrumentino looks like an awesome Python library, but I'm having some trouble figuring out how to compile controlino and put it on the Arduino. I am a mechanical engineer able to handle the Python parts, but I'm not familiar with Eclipse or Arduino.

I have tried importing the controlino project into Eclipse and moving files around to try to match the paths Eclipse is giving warnings about, but have had no success so far. When I try to build, I get lots of warnings like `Invalid project path: Include path not found (controlino/arduino/variant)` and one error `make: *** No rule to make target 'clean'`. I'm not familiar with Eclipse, so I'm not sure what these mean or how to fix them :cry:.

Can you give me any advice on how to get past these issues in Eclipse? Alternatively, is there a list of explicit steps I can follow to build controlino and get it on the Arduino? Honestly, it would be most helpful if there was a definitive list of steps. Thank you very much for your work on this, and I am excited to work with it once I get past this issue.

**Comment by yoelk** [comment]
Hi Daniel,
Are you the same Daniel that recently wrote me (from uni-weimar)>

Anyway, eclipse is definitely not a must.

Controlino is a single file, so you can easily open it with the normal
Arduino editor, and use it to compile and upload Controlino to your arduino
device.
It would be good if you look a bit in the Controlino code, at least in its
beginning.
There is a list of definitions you should set before compiling, such as
which Arduino board you're using, which libraries you want to use etc.
If you want to use the PID library, for example, you need to have it
"installed" in the appropriate place, so the "#include" statement will find
it.

If you're still not successful doing it this way, please let me know, with
the error you get from the normal Arduino editor/loader.

Good luck,
Joel

**Comment by daniellikessoccer** [comment]
I am no longer using this account. 
Please change my email address and resend your message to danielurbant@gmail.com

**Comment by snarfums** [comment]
I'm having a similar issue.  I'm using "sketch" to compile + load the controlino.cpp file onto my arduino uno and it's unable to load the libraries (SoftwareSerial is the one I'm using).

sketch uses serveral things to load libraries, but for .cpp it appears I need both the SoftwareSerial.cpp file and the SoftwareSerial.h file, otherwise the #include "SoftwareSerial.h" line fails inside sketch.

If you're not using sketch or want to test/see what I'm doing, here's the sketch library loading documentation: http://arduino.cc/en/guide/libraries

Can you include the .h/.cpp files for the controlino libraries or list the source location/software you're using for them?

**Comment by daniellikessoccer** [comment]
I am no longer using this account. 
Please change my email address and resend your message to danielurbant@gmail.com

**Comment by snarfums** [comment]
I found out why I was having issues. Possibly old software, probably how I loaded the file into sketch.
1. I was running a fairly old version of what they now call "Arduino Editor", which was called "sketch" at one time.  I upgraded to Arduino Editor 1.62 (the latest)
2. To do that upgrade, I had to go from java 7.x (open source) to 8 (oracle). Lots of issues on the Arduino Editor forums about startup issues and using java 1.8 is the "fix".
3. As suggested above, but I really didn't pick it out when I first read it, is how you need to load controlino.cpp into the Arduino Editor.  What *didn't* work for me was to include it via the "add file" option. It will load, but will not compile (it cannot find SoftwareSerial.h). What *did* work was to make a copy of controlino.cpp and call this copy controlino.ino, put this in your sketchbook directory (for ease of the next step), then load it directly via file -> sketchbook-> controlino

After that it compiles and I loaded it into the Arduino.

**Comment by yoelk** [comment]
Hi Snarfums,
So, do I understand your issue is resolved?
Sorry for taking so long, I've been away last week.

**Comment by snarfums** [comment]
Yes: Issue resolved!  I figured I'd post all the details in case anyone else ran into similar issues/questions.

**Comment by daniellikessoccer** [comment]
I am no longer using this account. 
Please change my email address and resend your message to danielurbant@gmail.com
