### ISSUE TITLE
Using a pid-controlled heater

### ISSUE THREAD

**Issue by meeschka** [yoelk/Instrumentino#7]
Hello again,
I am trying to control a small heating element based on readings from a thermistor. However, Whenever I try to "set" the heater using methods or sequences, it runs for about 15-30 seconds and then stops. Likewise, setting the heating element temperature, or simply turning it off/on through digital pins by adjusting the sidebar seems to make it think for 15-30 seconds, but no real change... I am using the pid function included in the instrumentino package, and my thermistors are reading correctly, so I'm wondering if I'm just not understanding how the pid system works.
If I set the heater in a method, and then run it, how long should it go for? Until it reaches the desired temperature? Until the system is stopped?  A I missing something obvious about how to use the pid system?
Cheers,
Michelle

**Comment by yoelk** [comment]
Hi Michelle, can you send me your python system description file?
I've also upgraded since then both Instrumentino and Controlino (the sketch
that runs on the Arduino), so you might want to download the new version.

Send me the file and I'll see if I can find something.

Joel

**Comment by meeschka** [comment]
Hi Joel,
Part of my problems were resolved with the new Instrumentino and Controlino files. For the rest, I realized it has to do with how I am mapping the fraction output to thermistor values, which are non-linear with respect to resistance. Long story short: I'm going to play around with it for a while, see what I can do, will keep you posted. 
Thanks :)
Michelle

**Comment by yoelk** [comment]
Great!
I'm happy it worked out for you.
